---
- name: Ensure /srv/z3950 dirs exist
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: apache
    group: apache
    recurse: yes
  with_items:
    - /srv/z3950/etc
    - /srv/z3950/cgi-bin

- name: Install apc.ini
  copy:
    mode: 0644
    owner: root
    group: root
    src: apc.ini
    dest: /etc/php.d

- name: Install apc.conf
  copy:
    mode: 0644
    owner: root
    group: root
    src: apc.conf
    dest: /etc/httpd/conf.d    

- name: Install z3950 gateway templates
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{ item.mode }}"
  with_items:
    - src: srv_z3950.conf.j2
      dest: /srv/z3950/etc/srv_z3950.conf
      mode: 0644
    - src: config.php.j2
      dest: /srv/z3950/cgi-bin/config.php
      mode: 0755

- name: Install z3950 gateway files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{ item.mode }}"
  with_items:
    - src: index.php
      dest: /srv/z3950/cgi-bin/index.php
      mode: 0755
