---
# tasks file for alma-z3950-gateway

- include: yum.yml
  tags: alma_z3950_gateway_yum
  sudo: yes

- include: pear.yml
  tags: alma_z3950_gateway_pear
  sudo: yes

- include: configure.yml
  tags: alma_z3950_gateway_configure
  sudo: yes

- include: assets.yml
  tags: alma_z3950_gateway_assets
  sudo: yes
