---
# tasks file for alma-z3950-gateway

- include: yum.yml
  tags: alma_z3950_gateway_yum
  become: true

- include: pear.yml
  tags: alma_z3950_gateway_pear
  become: true

- include: configure.yml
  tags: alma_z3950_gateway_configure
  become: true

- include: assets.yml
  tags: alma_z3950_gateway_assets
  become: true
